addSbtPlugin("de.heikoseeberger" % "sbt-header"         % "5.6.0")
addSbtPlugin("com.codecommit"    % "sbt-github-actions" % "0.14.2")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"       % "2.4.6")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"      % "1.9.3")
addSbtPlugin("org.scoverage"     % "sbt-coveralls"      % "1.3.1")
addSbtPlugin("com.github.sbt"    % "sbt-ci-release"     % "1.5.10")
